// Semi-Colon separated VaArgs
#define scsvargs(...) __VA_OPT__(scsvargs1(__VA_ARGS__))

// clang-format off
#define scsvargs1(a, ...) a ; __VA_OPT__(scsvargs2(__VA_ARGS__))
#define scsvargs2(a, ...) a ; __VA_OPT__(scsvargs3(__VA_ARGS__))
#define scsvargs3(a, ...) a ; __VA_OPT__(scsvargs4(__VA_ARGS__))
#define scsvargs4(a, ...) a ; __VA_OPT__(scsvargs5(__VA_ARGS__))
#define scsvargs5(a, ...) a ; __VA_OPT__(scsvargs6(__VA_ARGS__))
#define scsvargs6(a, ...) a ; __VA_OPT__(scsvargs7(__VA_ARGS__))
#define scsvargs7(a, ...) a ; __VA_OPT__(scsvargs8(__VA_ARGS__))
#define scsvargs8(a, ...) a ; __VA_OPT__(scsvargs9(__VA_ARGS__))
#define scsvargs9(a, ...) a ; __VA_OPT__(scsvargs10(__VA_ARGS__))
#define scsvargs10(a, ...) a ; __VA_OPT__(scsvargs11(__VA_ARGS__))
#define scsvargs11(a, ...) a ; __VA_OPT__(scsvargs12(__VA_ARGS__))
#define scsvargs12(a, ...) a ; __VA_OPT__(scsvargs13(__VA_ARGS__))
#define scsvargs13(a, ...) a ; __VA_OPT__(scsvargs14(__VA_ARGS__))
#define scsvargs14(a, ...) a ; __VA_OPT__(scsvargs15(__VA_ARGS__))
#define scsvargs15(a, ...) a ; __VA_OPT__(scsvargs16(__VA_ARGS__))
#define scsvargs16(a, ...) a ; __VA_OPT__(scsvargs17(__VA_ARGS__))
#define scsvargs17(a, ...) a ; __VA_OPT__(scsvargs18(__VA_ARGS__))
#define scsvargs18(a, ...) a ; __VA_OPT__(scsvargs19(__VA_ARGS__))
#define scsvargs19(a, ...) a ; __VA_OPT__(scsvargs20(__VA_ARGS__))
#define scsvargs20(a, ...) a ; __VA_OPT__(scsvargs21(__VA_ARGS__))
#define scsvargs21(a, ...) a ; __VA_OPT__(scsvargs22(__VA_ARGS__))
// clang-format on
